// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/engapp/00-app.tsx": () => import("../components/mockups/engapp/00-app.tsx"),
  "./components/mockups/engapp/01-splash.tsx": () => import("../components/mockups/engapp/01-splash.tsx"),
  "./components/mockups/engapp/02-onboarding-language.tsx": () => import("../components/mockups/engapp/02-onboarding-language.tsx"),
  "./components/mockups/engapp/03-onboarding-exam.tsx": () => import("../components/mockups/engapp/03-onboarding-exam.tsx"),
  "./components/mockups/engapp/04-onboarding-daily.tsx": () => import("../components/mockups/engapp/04-onboarding-daily.tsx"),
  "./components/mockups/engapp/05-onboarding-style.tsx": () => import("../components/mockups/engapp/05-onboarding-style.tsx"),
  "./components/mockups/engapp/06-feed.tsx": () => import("../components/mockups/engapp/06-feed.tsx"),
  "./components/mockups/engapp/07-word-detail.tsx": () => import("../components/mockups/engapp/07-word-detail.tsx"),
  "./components/mockups/engapp/08-bookmarks.tsx": () => import("../components/mockups/engapp/08-bookmarks.tsx"),
  "./components/mockups/engapp/09-known.tsx": () => import("../components/mockups/engapp/09-known.tsx"),
  "./components/mockups/engapp/10-revisit.tsx": () => import("../components/mockups/engapp/10-revisit.tsx"),
  "./components/mockups/engapp/11-stats.tsx": () => import("../components/mockups/engapp/11-stats.tsx"),
  "./components/mockups/engapp/12-profile.tsx": () => import("../components/mockups/engapp/12-profile.tsx"),
  "./components/mockups/engapp/13-settings.tsx": () => import("../components/mockups/engapp/13-settings.tsx"),
  "./components/mockups/engapp/14-style-picker.tsx": () => import("../components/mockups/engapp/14-style-picker.tsx"),
  "./components/mockups/engapp/15-browse.tsx": () => import("../components/mockups/engapp/15-browse.tsx"),
  "./components/mockups/engapp/16-search.tsx": () => import("../components/mockups/engapp/16-search.tsx"),
  "./components/mockups/engapp/17-share-preview.tsx": () => import("../components/mockups/engapp/17-share-preview.tsx"),
  "./components/mockups/engapp/18-paywall.tsx": () => import("../components/mockups/engapp/18-paywall.tsx"),
  "./components/mockups/engapp/19-empty.tsx": () => import("../components/mockups/engapp/19-empty.tsx"),
  "./components/mockups/engapp/20-error.tsx": () => import("../components/mockups/engapp/20-error.tsx"),
  "./components/mockups/engapp/21-signin.tsx": () => import("../components/mockups/engapp/21-signin.tsx")
};
